Create 2024 weekly template and blocks
parameter1/pmmi-media-group-newsletters pull request #127
Opened 2023-11-13 14:58 UTC by jwade1327

![screencapture-localhost-22095-templates-pw-weekly-2023-11-13-08_50_35](https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/0143bf43-6f13-49ff-94cf-2dd890252445)

2023-11-13 14:59 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PW, CMP, HCP, OEM, PFW, Mundo Newsletters & PW Weekly NL 2024](https://trello.com/c/WSn92NAA/649-pw-cmp-hcp-oem-pfw-mundo-newsletters-pw-weekly-nl-2024)

2023-11-13 15:59 UTC, Shinsina requested changes
You are going to need to use the `marko-web-query` component using the `all-published-content` query something similar to either of the following: https://github.com/parameter1/pmmi-media-group-websites/pull/588 https://github.com/parameter1/pmmi-media-group-websites/pull/575 you'll likely need to pass the siteId via the query parameters as well as using `includeContentTypes` to include the necessary content types per block.

2023-11-14 18:47 UTC, Shinsina requested changes
I'm seeing a lot of new components here with variables being declared within them that go entirely unused, rather than making a comment on each one (since there is a lot of them here). I'm making this blanket comment instead.

Check each file added/updated here and verify that anything that gets declared gets used and moreover verify that the input to each component is only having things passed in that are used, this can be improved by declaring what input a component allows in it's respective `marko.json` file, if you have any questions or need some clarification here let me know :)

2023-11-14 20:53 UTC, Shinsina requested changes
Verify that removing these doesn't inherently break anything here, additionally try and ensure input isn't being unnecessarily passed in when it's not used/isn't necessary.

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024-head.marko
> +$ const { newsletter, date } = input;
`website` and `date` appear to go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/ad/emailx.marko
> +import { getAsObject, get } from "@parameter1/base-cms-object-path";
`get` appears to go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/ad/emailx.marko
> +$ const { name, alias } = adUnit;
both `name` and `alias` go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/ad/nativex.marko
> +import queryFragment from "../../../../graphql/fragments/content-list";
`queryFragment` goes unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/body-wrapper.marko
> +        <common-2024-header-block newsletter=newsletter date=date />
I believe date goes unused in `packages/common/components/blocks/2024/header.marko` so date can be removed here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/body-wrapper.marko
> +        <common-2024-footer-block newsletter=newsletter date=date />
Both `newsletter` and `date` go unused in `packages/common/components/blocks/2024/footer.marko` so they can likely be removed here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/events.marko
> +$ const { newsletter, date } = input;
`newsletter` and `date` go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/header.marko
> +$ const { newsletter, date } = input;
`date` goes unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/promo.marko
> +$ const { newsletter, date, content, withImage, sectionName } = input;
`newsletter`, `date` and `sectionName` go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/blocks/2024/webinar.marko
> +$ const { newsletter, date } = input;
`newsletter` and `date` go unused here

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/layouts/2024-weekly.marko
> +import moment from "moment";
getAsArray, stripHtml, queryFragment and moment all go unused

2023-11-14 20:53 UTC, Shinsina commented on packages/common/components/layouts/2024-weekly.marko
> +$ const { newsletter, date, sectionName } = input.data;
`website` and `sectionName` go unused here

2023-11-14 20:53 UTC, Shinsina commented on tenants/all/templates/pw-weekly.marko
> +<common-2024-weekly-layout data=data />
`get`, `date` and `newsletterConfig` go unused here. By proxy `newsletter` can also be removed`

2023-11-14 21:27 UTC, Shinsina approved these changes

2023-11-14 21:27 UTC, merged