Mundo date revisions & styling adjustments for promo & stat blocks
parameter1/pmmi-media-group-newsletters pull request #136
Opened 2023-12-19 21:38 UTC by jwade1327

<img width="796" alt="Screen Shot 2023-12-19 at 2 15 58 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/b2cd22b6-c366-4d42-a6f9-5d941c3e6ee1">
<img width="744" alt="Screen Shot 2023-12-19 at 3 09 06 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/22052a12-d1b2-4aa7-bf9b-c8a0cb6aef9b">
<img width="771" alt="Screen Shot 2023-12-19 at 3 13 46 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/b254f2fd-bdf7-4bba-a4b5-30c2e929ed9f">
<img width="680" alt="Screen Shot 2023-12-19 at 3 13 54 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/77a7f4f1-915f-416a-8c2f-44e3087d2649">
<img width="382" alt="Screen Shot 2023-12-19 at 3 33 40 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/69d6b869-a40d-4a10-8bec-9a8223e09076">

2023-12-19 21:39 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PW, CMP, HCP, OEM, PFW, Mundo Newsletters 2024 Cont.](https://trello.com/c/yXbG2eL2/728-pw-cmp-hcp-oem-pfw-mundo-newsletters-2024-cont)

2023-12-20 14:20 UTC, Shinsina requested changes

2023-12-20 14:20 UTC, Shinsina commented on packages/common/components/blocks/2024/date-banner-mundo.marko
> +$ const { website, config, i18n } = out.global;
`website` goes unused here.

2023-12-20 19:34 UTC, Shinsina approved these changes

2023-12-20 19:34 UTC, merged