Remove duplicate code in meta data
parameter1/pmmi-media-group-newsletters pull request #169
Opened 2024-03-14 20:56 UTC by jwade1327

<img width="684" alt="Screenshot 2024-03-14 at 3 53 52 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/ed57e700-a6ad-4bc2-8106-9e1cca4c6873">
<img width="1640" alt="Screenshot 2024-03-14 at 3 53 41 PM" src="https://github.com/parameter1/pmmi-media-group-newsletters/assets/64623209/bc497d6e-c8cd-4463-96a8-8f1da89dbe53">

2024-03-14 20:56 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [2024 Newsletter Revisions - feedback](https://trello.com/c/c830COni/820-2024-newsletter-revisions-feedback)

2024-03-15 17:49 UTC, Shinsina requested changes

2024-03-15 17:49 UTC, Shinsina commented on packages/common/components/layouts/2024-daily.marko
> +<marko-newsletter-root>
Removing `titlle` here is fine as that would be duplicative given it's in `2024-head.marko` however `date` is not included in `2024-head.marko` and should likely remain included here so we aren't removing data here.

2024-03-15 19:08 UTC, Shinsina approved these changes

2024-03-15 19:08 UTC, merged